/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmbitosRouteImport } from './routes/ambitos'
import { Route as AnsiedadRouteImport } from './routes/ansiedad'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as DejarDeFumarRouteImport } from './routes/dejar-de-fumar'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as SesionesRouteImport } from './routes/sesiones'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as EmpresasContactoRouteImport } from './routes/empresas.contacto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbitosRoute = AmbitosRouteImport.update({
  id: '/ambitos',
  path: '/ambitos',
  getParentRoute: () => rootRouteImport,
} as any)
const AnsiedadRoute = AnsiedadRouteImport.update({
  id: '/ansiedad',
  path: '/ansiedad',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const DejarDeFumarRoute = DejarDeFumarRouteImport.update({
  id: '/dejar-de-fumar',
  path: '/dejar-de-fumar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const SesionesRoute = SesionesRouteImport.update({
  id: '/sesiones',
  path: '/sesiones',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const EmpresasContactoRoute = EmpresasContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => EmpresasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambitos': typeof AmbitosRoute
  '/ansiedad': typeof AnsiedadRoute
  '/blog': typeof BlogRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/dejar-de-fumar': typeof DejarDeFumarRoute
  '/empresas': typeof EmpresasRouteWithChildren
  '/eventos': typeof EventosRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/reservar': typeof ReservarRoute
  '/sesiones': typeof SesionesRoute
  '/sobre-mi': typeof SobreMiRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/empresas/contacto': typeof EmpresasContactoRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambitos': typeof AmbitosRoute
  '/ansiedad': typeof AnsiedadRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/dejar-de-fumar': typeof DejarDeFumarRoute
  '/empresas': typeof EmpresasRouteWithChildren
  '/eventos': typeof EventosRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/reservar': typeof ReservarRoute
  '/sesiones': typeof SesionesRoute
  '/sobre-mi': typeof SobreMiRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/empresas/contacto': typeof EmpresasContactoRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambitos': typeof AmbitosRoute
  '/ansiedad': typeof AnsiedadRoute
  '/blog': typeof BlogRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/dejar-de-fumar': typeof DejarDeFumarRoute
  '/empresas': typeof EmpresasRouteWithChildren
  '/eventos': typeof EventosRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/reservar': typeof ReservarRoute
  '/sesiones': typeof SesionesRoute
  '/sobre-mi': typeof SobreMiRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/empresas/contacto': typeof EmpresasContactoRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambitos'
    | '/ansiedad'
    | '/blog'
    | '/como-funciona'
    | '/contacto'
    | '/dejar-de-fumar'
    | '/empresas'
    | '/eventos'
    | '/faq'
    | '/legal'
    | '/politica-de-cookies'
    | '/reservar'
    | '/sesiones'
    | '/sobre-mi'
    | '/blog/$slug'
    | '/empresas/contacto'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambitos'
    | '/ansiedad'
    | '/como-funciona'
    | '/contacto'
    | '/dejar-de-fumar'
    | '/empresas'
    | '/eventos'
    | '/faq'
    | '/legal'
    | '/politica-de-cookies'
    | '/reservar'
    | '/sesiones'
    | '/sobre-mi'
    | '/blog/$slug'
    | '/empresas/contacto'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/ambitos'
    | '/ansiedad'
    | '/blog'
    | '/como-funciona'
    | '/contacto'
    | '/dejar-de-fumar'
    | '/empresas'
    | '/eventos'
    | '/faq'
    | '/legal'
    | '/politica-de-cookies'
    | '/reservar'
    | '/sesiones'
    | '/sobre-mi'
    | '/blog/$slug'
    | '/empresas/contacto'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbitosRoute: typeof AmbitosRoute
  AnsiedadRoute: typeof AnsiedadRoute
  BlogRoute: typeof BlogRouteWithChildren
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactoRoute: typeof ContactoRoute
  DejarDeFumarRoute: typeof DejarDeFumarRoute
  EmpresasRoute: typeof EmpresasRouteWithChildren
  EventosRoute: typeof EventosRoute
  FaqRoute: typeof FaqRoute
  LegalRoute: typeof LegalRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  ReservarRoute: typeof ReservarRoute
  SesionesRoute: typeof SesionesRoute
  SobreMiRoute: typeof SobreMiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambitos': {
      id: '/ambitos'
      path: '/ambitos'
      fullPath: '/ambitos'
      preLoaderRoute: typeof AmbitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ansiedad': {
      id: '/ansiedad'
      path: '/ansiedad'
      fullPath: '/ansiedad'
      preLoaderRoute: typeof AnsiedadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dejar-de-fumar': {
      id: '/dejar-de-fumar'
      path: '/dejar-de-fumar'
      fullPath: '/dejar-de-fumar'
      preLoaderRoute: typeof DejarDeFumarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sesiones': {
      id: '/sesiones'
      path: '/sesiones'
      fullPath: '/sesiones'
      preLoaderRoute: typeof SesionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/empresas/contacto': {
      id: '/empresas/contacto'
      path: '/contacto'
      fullPath: '/empresas/contacto'
      preLoaderRoute: typeof EmpresasContactoRouteImport
      parentRoute: typeof EmpresasRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EmpresasRouteChildren {
  EmpresasContactoRoute: typeof EmpresasContactoRoute
}

const EmpresasRouteChildren: EmpresasRouteChildren = {
  EmpresasContactoRoute: EmpresasContactoRoute,
}

const EmpresasRouteWithChildren = EmpresasRoute._addFileChildren(
  EmpresasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbitosRoute: AmbitosRoute,
  AnsiedadRoute: AnsiedadRoute,
  BlogRoute: BlogRouteWithChildren,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactoRoute: ContactoRoute,
  DejarDeFumarRoute: DejarDeFumarRoute,
  EmpresasRoute: EmpresasRouteWithChildren,
  EventosRoute: EventosRoute,
  FaqRoute: FaqRoute,
  LegalRoute: LegalRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  ReservarRoute: ReservarRoute,
  SesionesRoute: SesionesRoute,
  SobreMiRoute: SobreMiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
